# Generated by Django 5.2.1 on 2025-07-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='reply',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
