# Generated by Django 5.2.1 on 2025-07-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_maintenance_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
