# Generated by Django 5.2.1 on 2025-06-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_maintenance_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(default='def', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='status',
            field=models.TextField(choices=[('PENDING', 'PENDING'), ('DELIVERED', 'DELIVERED')], default='PENDING'),
        ),
    ]
