# Generated by Django 5.2.1 on 2025-07-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_maintenance_image_alter_suggestion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='reply',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
