# Generated by Django 5.2.1 on 2025-06-01 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='sender',
            field=models.ForeignKey(default='tahi47@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
            preserve_default=False,
        ),
    ]
