# Generated by Django 5.2.1 on 2025-06-01 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_maintenance_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
    ]
