# Generated by Django 5.2.1 on 2025-06-01 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_maintenance_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='sender',
        ),
    ]
