# Generated by Django 5.2.1 on 2025-07-03 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_maintenance_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
    ]
