# Generated by Django 5.2.1 on 2025-08-02 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_maintenance_reply'),
        ('myapp', '0010_alter_maintenance_sender'),
    ]

    operations = [
    ]
