# Generated by Django 5.2.1 on 2025-08-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_merge_20250802_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='item',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='sender',
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='status',
            field=models.TextField(choices=[('PENDING', 'PENDING'), ('IN PROGRESS', 'IN PROGRESS'), ('RESOLVED', 'RESOLVED')], default='PENDING'),
        ),
    ]
